### ISSUE TITLE
otel-o11y-demo-tier1-1 container won't start in "main" branch

### ISSUE THREAD

**Issue by booyaa** [honeycombio/otel-o11y-demo#6]
Just wondering if this container is intentionally broken? If I switch to `auto-instrumented` the demo app works.

**Versions**

- repo  (git rev-list --max-count=1 HEAD):  `c96df65755051bb5d5eac16de5415378fb8ec573`
- docker (Rancher Desktop v1.16.0)

```
Client:
 Version:           27.2.1-rd
 API version:       1.45 (downgraded from 1.47)
 Go version:        go1.22.7
 Git commit:        cc0ee3e
 Built:             Tue Sep 10 15:41:09 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          26.1.5
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       411e817ddf710ff8e08fa193da80cb78af708191
  Built:            Fri Jul 26 17:51:06 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.14
  GitCommit:        2c9f5602f0ba3d9da1c2596322dfc4e156844890
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

**Steps to reproduce**

1. clone repo
2.  run `./run`

**Additional context**

Output from `./run` (only displaying start-up status)

```sh
[+] Running 8/8
 ✔ Network otel-o11y-demo_default             Created                              0.1s 
 ✔ Container otel-o11y-demo-queue-1           Healthy                             11.8s 
 ✔ Container otel-o11y-demo-db-1              H...                                11.8s 
 ✔ Container otel-o11y-demo-queue_consumer-1  Started                             11.2s 
 ✔ Container otel-o11y-demo-tier2-1           Started                             11.2s 
 ✘ Container otel-o11y-demo-tier1-1           Error                               12.5s 
 ✔ Container otel-o11y-demo-web-1             Created                              0.0s 
 ✔ Container otel-o11y-demo-waf-1             Created                              0.0s 
dependency failed to start: container otel-o11y-demo-tier1-1 exited (2)
```

Logs from failing container

```sh
docker logs otel-o11y-demo-tier1-
1
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/app.py", line 11, in <module>
    from opentelemetry import trace
ModuleNotFoundError: No module named 'opentelemetry'

Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/app.py", line 11, in <module>
    from opentelemetry import trace
ModuleNotFoundError: No module named 'opentelemetry'
```

**Comment by booyaa** [comment]
I've looked at this, and I think the given "main" branch should be completely void of any instrumentation importing non-existent libraries (not in requirements.txt) and enabling tracing is a bit premature. I'd be happy to create a PR to remove those libraries and the tracer annotations. Is this something that would be useful?
